# [Info]
site_name: Peixuan Wu's Land
site_url: https://yang-xijie.github.io
site_author: Peixuan Wu
site_description: Peixuan Wu's Land
# [UI]
## [top]
theme:
  name : material
  palette: 
  - scheme: default
    primary: deep purple
    accent: deep orange
    toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
  - scheme: slate # 夜间模式
    primary: indigo
    accent: deep orange
    toggle:
      icon: material/weather-sunny
      name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/Peixuan-Wu/peixuan-wu.github.io # 右上角点击跳转的链接
repo_name: peixuan-wu.github.io # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2022 Peixuan Wu # 左下角的版权声明
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/22835630/
      name: Bilibili | 之渊W # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Peixuan-Wu
      name: GitHub | Peixuan-Wu

# [Navigtion]
nav:
  - Home:
    - ./index.md
  - Note: 
    - Note/index.md
    - markdown: Note/markdown/markdownlearn.md
    - tips for material for mkdocs:
      - Getting started: Note/material/tips-for-material-for-mkdocs.md
      - what is Schema?: Note/material/what-is-Json-Schema.md
    - Algorithm and data structure:
      - Binary Tree: Note/Algorithm_datastructure/binaryTree.md
  - To:
    - Blog/index.md
    - Sun:
      - Blog/Diary2022/220511.md
      - Blog/Diary2023/230218.md
    - En_w:
      - Blog/En_writing/sample1.md
    - Article:
      - 与google researcher的对话: Blog/Article/Chole.md
  - Develop:
    - Develop/index.md
    - computer graphic:
      - 101-overview: Develop/CG/101overview.md
      - 101-Linear Algebra: Develop/CG/101LinearAlgebra.md
      - GPU是如何工作的?: Develop/CG/GPUpipline.md
  - Game:
    - Game/index.md
    - 杂谈:
      - 我的游戏历程: Game/ZaTan/gamePath.md
    - 天地劫:
      - Game/TDJ/index.md
    - 梦战:
      - Game/MZ/index.md
    - 原神:
      - Game/YuanShen/index.md
   
  - About:
    - About/index.md

# [Extensions]
plugins:
  - search # 现在还不支持中文搜索 支持之后可以设置语言
  - tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - mkdocs/javascripts/mathjax.js # latex支持
  - https://polyfill.io/v3/polyfill.min.js?features=es6 # latex支持
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # latex支持
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols

    
    
  

